# Generated by MathModel Skill scaffold generator.
from __future__ import annotations

from result_contract_io import run_question_scaffold


QUESTION = {
  "question_id": "Q1",
  "title": "问题一",
  "task_type": "机理/仿真与参数校准",
  "core_goal": "一维单电池瞬态自冷启动模型建立及验证",
  "baseline_model": "备注1的常温一维传热传质与电压模型",
  "main_model": "有限体积多相冷启动模型：水/冰相变、有效孔隙率与扩散、反应面积反馈",
  "backup_models": [
    "差分方程",
    "参数校准仿真",
    "情景模拟"
  ],
  "model_reason": "该问属于“机理/仿真与参数校准”任务，有限体积多相冷启动模型：水/冰相变、有效孔隙率与扩散、反应面积反馈 能在保留可解释性的同时承接题目约束：五层一维膜电极区域，低温水蒸气/液态水/冰分相。",
  "formula_requirements": [
    "定义状态变量与参数",
    "写出状态转移或动力学方程",
    "说明参数校准与情景设定"
  ],
  "validation": [
    "-20摄氏度校准少量参数，-25摄氏度留作独立验证",
    "温度、电压逐时残差和题定相对误差",
    "水质量与能量守恒、非负性、网格收敛、相变参数敏感性"
  ],
  "figures": [
    {
      "figure_id": "fig_q1_1",
      "title": "电压和温度实验/模型对照及残差",
      "purpose": "支撑Q1的模型结果、验证或敏感性分析",
      "expected_path": "paper_output/figures/fig_q1_1.png"
    },
    {
      "figure_id": "fig_q1_2",
      "title": "最大冰体积分数时间曲线和厚度剖面",
      "purpose": "支撑Q1的模型结果、验证或敏感性分析",
      "expected_path": "paper_output/figures/fig_q1_2.png"
    },
    {
      "figure_id": "fig_q1_3",
      "title": "冰相变参数敏感性与网格收敛对照",
      "purpose": "支撑Q1的模型结果、验证或敏感性分析",
      "expected_path": "paper_output/figures/fig_q1_3.png"
    }
  ],
  "paper_sections": [
    "问题一模型建立",
    "问题一结果分析",
    "问题一模型检验"
  ]
}


if __name__ == "__main__":
    raise SystemExit(run_question_scaffold(QUESTION))
